#!/bin/bash

. gem_script
. gem_build

function gem_v_SetDefaults
{
	gem_build_SetDefaults;

	gem_download_src=1

	# Need gnu extensions for compile asm code.
	gem_c_standard="-std=gnu11"	# c90, c99, c11, gnu90, gnu99, gnu11

#	gem_build_script="cmake"
	gem_build_script="autotools"
#	gem_build_script="meson"

	# Common Defaults
	if [[ $(uname -s) == "MINGW64"* ]]; then	# MinGW shell on Windows.
		gem_host=mingw
#		gem_host=msvc
	elif [[ $(uname -s) == "CYGWIN"* ]]; then	# MinGW shell on Windows.
		gem_host=cygwin
#		gem_host=mingw
	elif [[ $(uname -s) == "Linux"* ]]; then	# Linux shell.
		gem_host=linux
#		gem_host=mingw
#		gem_host=android_arm64_v8a
	fi

	gem_build_type=release
#	gem_build_type=debug

	gem_flags_configure=
	gem_flags_c=
	gem_flags_cpp=
	gem_flags_cxx=
	gem_flags_ld=


	gem_filename_pkg=libiconv
	gem_filename_version=1.16
	gem_filename_exten=tar.gz
	gem_filename_base=${gem_filename_pkg}-${gem_filename_version}
	gem_filename_archive=${gem_filename_base}.${gem_filename_exten}
	gem_filename_url=http://ftp.gnu.org/pub/gnu/libiconv/${gem_filename_archive}
}

function gem_v_DownloadSource
{
	# Download
	if [[ ! -f ${gem_filename_archive} ]]; then
		wget -c ${gem_filename_url}
		if [[ $? != 0 ]]; then
			gem_v_Error "ERROR: gem_v_DownloadSource: wget failed to download source archive: ${gem_filename_url}"
		fi
	fi
	# Decompress
	if [[ -d ${gem_fullpath_src} ]]; then
		gem_v_Msg "ALERT: src directory already exists.  Archive not uncompressed."
	else
		gem_script_mkdir -p ${gem_fullpath_src}
		gem_flags_tar="<undefined>"
		if [[ ${gem_filename_exten} == *".gz"* ]]; then
			gem_flags_tar="xzf"
		elif  [[ ${gem_filename_exten} == *".xz"* ]]; then
			gem_flags_tar="xf"
		fi
		if [[ ${gem_flags_tar} == "<undefined>" ]]; then
			gem_v_Error "ERROR: gem_v_DownloadSource: Unable to decompress downloaded file with extension \"${gem_filename_exten}\"."
		fi
		tar -${gem_flags_tar} ${gem_filename_archive} -C ${gem_fullpath_src}
		if [[ $? != 0 ]]; then
			gem_v_Error "ERROR: gem_v_DownloadSource: Failed to uncompress the source archive: ${gem_filename_archive}"
		fi
		gem_script_cp -rf ${gem_fullpath_src}/${gem_filename_base}/* ${gem_fullpath_src}
		gem_script_rm -rf ${gem_fullpath_src}/${gem_filename_base}
	fi

	gem_build_DownloadSource
}

function gem_v_OnConfigure
{
	# gem_flags_configure, gem_flags_c, gem_flags_cpp, gem_flags_cxx,
	# gem_flags_ld. To remove a flag:
	# flags=$(printf '%s\n' "${flags//-byebye/}")

	gem_flags_configure=" \
--enable-relocatable \
--enable-static \
--disable-rpath \
LIBS="-liconv" \
${gem_flags_configure}"

	gem_v_DebugDumpVars
	gem_build_OnConfigure
}

function gem_v_build_CommandLine_Build
{
	gem_build_CommandLine_Build
#	printf "\ngem_cmd_line_build=\n\n${gem_cmd_line_build}\n\n"
}

function gem_v_OnBuild
{
	# gem_flags_configure, gem_flags_c, gem_flags_cpp, gem_flags_cxx,
	# gem_flags_ld. To remove a flag:
	# flags=$(printf '%s\n' "${flags//-byebye/}")
	gem_v_DebugDumpVars
	gem_build_OnBuild
}

function gem_v_OnInstall
{
	# gem_flags_configure, gem_flags_c, gem_flags_cpp, gem_flags_cxx,
	# gem_flags_ld. To remove a flag:
	# flags=$(printf '%s\n' "${flags//-byebye/}")
	gem_build_OnInstall


}

function gem_v_OnUninstall
{
	gem_build_OnUninstall
}

function gem_v_OnClean
{
	# gem_flags_configure, gem_flags_c, gem_flags_cpp, gem_flags_cxx,
	# gem_flags_ld. To remove a flag:
	# flags=$(printf '%s\n' "${flags//-byebye/}")
	gem_build_Cmd_OnClean
}

# =============================================================================
#                                       gem_Main
# =============================================================================
function gem_v_OnArg
{
	arg=$(echo ${1} | tr '[A-Z]' '[a-z]')	# Lowercase args.
	case ${arg} in
		*)	gem_build_OnArg "$@" ;	return $?
	esac
}


function gem_v_Main
{
	gem_build_Main "$@"
}

gem_v_Main $@
