#!/bin/bash
#  ___________                           __________
# /\   _______\                         /\   ______\
# \ \  \______/_     ___   ____ ____ ___\ \  \_____/_     ___   ___ ___  ______    ___    ___
#  \ \  \ /\__  \  /'___`\/\   V    V   \\ \_______  \  /'   `\/\  \\  \/\   __\/' ._`\ /'___`\
#   \ \  \\/__\  \/\  ___/\ \  \/\  \/\  \\/_______\  \/\  \\  \ \  \\  \ \  \ /\  \__//\  ___/
#    \ \__________\ \____\ \ \__\ \__\ \__\ /\_________\ \_____/\ \______\ \__\\ \____/\ \____\
#     \/__________/\/____/  \/__/\/__/\/__/ \/_________/\/____/  \/______/\/__/ \/___/  \/____/


. gem_script
. gem_build

function gem_v_SetDefaults
{
	gem_build_SetDefaults;

	# Need gnu extensions for compile asm code.
	# Tried: c11, c90
	gem_c_standard="-std=gnu90"	# c90, c99, c11, c17, c2x, gnu90, gnu99, gnu11

#	gem_build_script="cmake"
	gem_build_script="autotools"
#	gem_build_script="meson"

	# Common Defaults
	if [[ ${gem_os} == "MINGW64"* ]]; then	# MinGW shell on Windows.
		gem_host=mingw
#		gem_host=msvc
	elif [[ ${gem_os} == "CYGWIN"* ]]; then	# Cygwin shell on Windows.
		gem_host=cygwin
#		gem_host=mingw
	elif [[ ${gem_os} == "Linux"* ]]; then	# Linux shell.
		gem_host=linux
#		gem_host=mingw
#		gem_host=android_arm64_v8a
	fi

	gem_build_type=release
#	gem_build_type=debug

	# The package url must be in the following format:
	# <url parent>/<package name>-<version>.tar.<extension>
	gem_filename_url=http://ftp.gnu.org/pub/gnu/libiconv/libiconv-1.16.tar.gz

	# Set build flags.
#-flto \
#-fPIC \

#--enable-relocatable \
#--enable-static \
#--disable-rpath \

	gem_flags_configure="${gem_flags_configure}"
	gem_flags_c="${gem_flags_c}"
	gem_flags_cpp="${gem_flags_cpp}"
	gem_flags_cxx="${gem_flags_cxx}"
	gem_flags_ld="${gem_flags_ld}"
	gem_flags_common="${gem_flags_common}"
}

function gem_v_DownloadSource
{
	gem_build_DownloadSource
}

function gem_v_OnConfigure
{
	gem_v_DebugDumpVars
	gem_build_OnConfigure
}

function gem_v_OnCommandLine_Configure_Autotools
{
	gem_v_DebugDumpVars
	gem_build_OnCommandLine_Configure_Autotools
}

function gem_v_OnBuild
{
	gem_v_DebugDumpVars
	gem_build_OnBuild
}

function gem_v_build_OnCommandLine_Build
{
	gem_build_OnCommandLine_Build
}

function gem_v_OnInstall
{
	gem_build_OnInstall
}

function gem_v_OnUninstall
{
#	gem_build_OnUninstall

	# build a colon-separated list of all files installed, less the
	# gem_fullpath_install prefix.
	if [[ ${gem_os} == "MINGW64"* || ${gem_os} == "CYGWIN"* ]]; then	# Cygwin shell on Windows.
		local gem_colon_separated_list="\
bin/libcharset-1.dll:\
bin/cygcharset-1.dll:\
bin/libiconv-2.dll:\
bin/cygiconv-2.dll:\
bin/iconv.exe:\
include/iconv.h:\
include/libcharset.h:\
include/localcharset.h:\
lib/libcharset.a:\
lib/libcharset.dll.a:\
lib/libcharset.la:\
lib/libiconv.a:\
lib/libiconv.dll.a:\
lib/libiconv.la:\
share/doc/iconv.1.html:\
share/doc/iconv.3.html:\
share/doc/iconv_close.3.html:\
share/doc/iconv_open.3.html:\
share/doc/iconv_open_into.3.html:\
share/doc/iconvctl.3.html:\
share/man/man1/iconv.1:\
share/man/man3/iconv.3:\
share/man/man3/iconv_close.3:\
share/man/man3/iconv_open.3:\
share/man/man3/iconv_open_into.3:\
share/man/man3/iconvctl.3"
	elif [[ ${gem_os} == "Linux" ]]; then	# Linux shell.
		gem_v_Error "Uninstall not yet implemented for Linux."
	else
		gem_v_Error "Build platform not supported: ${gem_os}"
	fi

	local gem_ifs_saved=${IFS}
	IFS=":"
	for gem_file in ${gem_colon_separated_list}
	do
		gem_fullpath_installed_file=${gem_fullpath_install}/${gem_file}
		if [[ -f ${gem_fullpath_installed_file} ]]; then
			gem_script_rm ${gem_fullpath_installed_file}
		fi
	done
	IFS=${gem_ifs_saved}

	local gem_space_separated_list="af bg ca cs da de el eo es et fi fr ga gl hr hu id it ja lt nl pl pt_BR rm ro ru sk sl sq sr sv tr uk vi wa zh_CN zh_TW"
	local gem_ifs_saved=${IFS}
	IFS=" "
	for gem_lang in ${gem_space_separated_list}
	do
		gem_fullpath_installed_file=${gem_fullpath_install}/share/locale/${gem_lang}/LC_MESSAGES/libiconv.mo
		if [[ -f ${gem_fullpath_installed_file} ]]; then
			gem_script_rm ${gem_fullpath_installed_file}
		fi
		gem_script_rmdir_IfEmpty ${gem_fullpath_install}/share/locale/${gem_lang}/LC_MESSAGES
		gem_script_rmdir_IfEmpty ${gem_fullpath_install}/share/locale/${gem_lang}
	done
	IFS=${gem_ifs_saved}

	gem_script_rmdir_IfEmpty ${gem_fullpath_install}/bin
	gem_script_rmdir_IfEmpty ${gem_fullpath_install}/include
	gem_script_rmdir_IfEmpty ${gem_fullpath_install}/lib
	gem_script_rmdir_IfEmpty ${gem_fullpath_install}/share/doc
	gem_script_rmdir_IfEmpty ${gem_fullpath_install}/share/man/man1
	gem_script_rmdir_IfEmpty ${gem_fullpath_install}/share/man/man3
	gem_script_rmdir_IfEmpty ${gem_fullpath_install}/share/man
	gem_script_rmdir_IfEmpty ${gem_fullpath_install}/share/locale
	gem_script_rmdir_IfEmpty ${gem_fullpath_install}/share
}

function gem_v_OnClean
{
	gem_build_OnClean
}

# =============================================================================
#                                       gem_Main
# =============================================================================
function gem_v_OnArg
{
	arg=$(echo ${1} | tr '[A-Z]' '[a-z]')	# Lowercase args.
	case ${arg} in
		*)	gem_build_OnArg "$@" ;	return $?
	esac
}

function gem_v_Main
{
	gem_build_Main "$@"
}
gem_v_Main $@
