#!/bin/bash
#  ___________                           __________
# /\   _______\                         /\   ______\
# \ \  \______/_     ___   ____ ____ ___\ \  \_____/_     ___   ___ ___  ______    ___    ___
#  \ \  \ /\__  \  /'___`\/\   V    V   \\ \_______  \  /'   `\/\  \\  \/\   __\/' ._`\ /'___`\
#   \ \  \\/__\  \/\  ___/\ \  \/\  \/\  \\/_______\  \/\  \\  \ \  \\  \ \  \ /\  \__//\  ___/
#    \ \__________\ \____\ \ \__\ \__\ \__\ /\_________\ \_____/\ \______\ \__\\ \____/\ \____\
#     \/__________/\/____/  \/__/\/__/\/__/ \/_________/\/____/  \/______/\/__/ \/___/  \/____/


. gem_script
. gem_build

function gem_build_v_SetDefaults
{
	gem_build_SetDefaults;

	gem_c_standard="-std=c99"	# c90, c99, c11, gnu90, gnu99, gnu11

	gem_build_script="cmake"
#	gem_build_script="autotools"
#	gem_build_script="meson"

	# Common Defaults
	if [[ ${gem_os} == "MINGW64"* ]]; then	# MinGW shell on Windows.
		gem_host=mingw
#		gem_host=msvc
	elif [[ ${gem_os} == "CYGWIN"* ]]; then		# Cygwin shell on Windows.
		gem_host=cygwin
#		gem_host=mingw
	elif [[ ${gem_os} == "Linux"* ]]; then	# Linux shell.
		gem_host=linux
#		gem_host=mingw
#		gem_host=android_arm64_v8a
	fi

	gem_build_type=release
#	gem_build_type=debug

	# Set build flags.
	gem_flags_configure="${gem_flags_configure}"
	gem_flags_c="${gem_flags_c}"
	gem_flags_cpp="${gem_flags_cpp}"
	gem_flags_cxx="${gem_flags_cxx}"
	gem_flags_ld="${gem_flags_ld}"
	gem_flags_common="${gem_flags_common}"
}

function gem_build_v_DownloadSource
{
	if [[ -d ./ogre || -d ./src ]]; then
		gem_script_v_Error "The source tree already exists.  Defying order to download."
	fi
	git clone --depth 1 --recursive --branch v1.12.4 https://github.com/OGRECave/ogre.git

	if [[ -d ./ogre && ! -d ./src ]]; then
		mv ./ogre ./src
	fi
}

function gem_build_v_OnCommandLine_Configure_CMake
{
	gem_cmd_line_configure="${gem_cmd_line_configure} \
-DOGRE_BUILD_COMPONENT_CSHARP=FALSE \
-DOGRE_BUILD_COMPONENT_PYTHON=FALSE \
-DOGRE_BUILD_TOOLS=FALSE"

	# On Linux, ~/gem/local/src/ogre-1.12.4/src/CMake/Dependencies.cmake
	# refuses to download and build SDL, as it does on other platforms.  As
	# such, we build sdl2 separately, then point to it.
	if [[ ${gem_os} == "Linux"* ]]; then
# SDL2_BINARY=
	gem_cmd_line_configure="${gem_cmd_line_configure} \
-DSDL2MAIN_LIBRARY=~/gem/local_x86_64-pc-linux-gnu/release/lib/libSDL2main.a \
-DSDL2_INCLUDE_DIR=~/gem/local_x86_64-pc-linux-gnu/release/include/SDL2 \
-DSDL2_LIBRARY_TEMP=~/gem/local_x86_64-pc-linux-gnu/release/lib/libSDL2.a"
	fi

# Didn't find the missing -ldl error while cross compiling.  I think installing
# mingw64-dlfcn or mingw64-dlfcn-static is the correct fix.

#	if [[ ${gem_os} == "Linux"*  && ${gem_host} == "mingw" ]]; then
#		gem_flags_ld="-lpsapi ${gem_flags_ld}"
#	fi

	gem_build_OnCommandLine_Configure_CMake

#	echo ${gem_cmd_line_configure} ; exit
}

function gem_build_v_OnConfigure
{
	gem_build_v_DebugDumpVars
	gem_build_OnConfigure
}

function gem_build_v_OnCommandLine_Build
{
	gem_build_OnCommandLine_Build

#	echo ${gem_cmd_line_build} ; exit
}

function gem_build_v_OnBuild
{
	gem_build_v_DebugDumpVars
	gem_build_OnBuild
}

function gem_build_v_OnInstall
{
	gem_build_OnInstall

	if [[ ${gem_os} == "MINGW64"* ]]; then	# MinGW shell on Windows.
		gem_script_cp ${gem_fullpath_install}/bin/libzlib1.dll ${gem_fullpath_install}/bin/zlib1.dll 
		gem_script_cp ${gem_fullpath_build}/zziplib-develop/zzip/libzzip-0.dll ${gem_fullpath_install}/bin/libzzip-0.dll
	elif [[ ${gem_os} == "Linux"* ]]; then	# Linux shell.
		if [[ ${gem_host} == "linux" ]]; then
			gem_script_cp ${gem_fullpath_build}/Dependencies/lib64/libzzip-0.so ${gem_fullpath_install}/lib
			gem_script_cp ${gem_fullpath_build}/Dependencies/lib64/libzzip-0.so.13 ${gem_fullpath_install}/lib
			gem_script_cp ${gem_fullpath_build}/Dependencies/lib64/libzzip-0.so.13.0.69 ${gem_fullpath_install}/lib
		elif [[ ${gem_host} == "mingw" ]]; then
			gem_script_cp ${gem_fullpath_build}/zziplib-develop/zzip/libzzip-0.dll ${gem_fullpath_install}/bin/libzzip-0.dll
		fi
	fi
}

function gem_build_v_OnUninstall
{
	gem_build_OnUninstall
}

function gem_build_v_Cmd_Clean
{
	gem_build_Cmd_Clean
}

# =============================================================================
#                                       gem_Main
# =============================================================================
function gem_build_v_OnArg
{
	arg=$(echo ${1} | tr '[A-Z]' '[a-z]')	# Lowercase args.
	case ${arg} in
		*)	gem_build_OnArg "$@" ;	return $?
	esac
}


function gem_build_v_Main
{
	gem_build_Main "$@"
}
gem_build_v_Main $@
