#!/bin/bash

# Platform
CROSS_COMPILE_MINGW_ON_LINUX=0

if [[ $(uname -s) == "MINGW64_NT-10.0" ]] || [[ $CROSS_COMPILE_MINGW_ON_LINUX == 1 ]]; then
	printf "Building for MinGW...\n"
	GNU_COMPILER=x86_64-w64-mingw32-g++
	EXECUTABLE_FILE_EXT=.exe
	MINGW_STATIC_LIBS="-static-libstdc++ -static-libgcc -static -lpthread"
else
	printf "Building for Linux...\n"
	GNU_COMPILER=g++
fi

# Clean
rm -f main main.exe

# Build
$GNU_COMPILER main.cpp -o main${EXECUTABLE_FILE_EXT} -Wall $MINGW_STATIC_LIBS



