#!/bin/bash

. gem_script
. gem_build

function gem_build_v_SetDefaults
{
	gem_build_SetDefaults;

	gem_download_src=0

	# Need gnu extensions for compile asm code.
	gem_c_standard="-std=gnu11"	# c90, c99, c11, gnu90, gnu99, gnu11

#	gem_build_script="cmake"
	gem_build_script="autotools"
#	gem_build_script="meson"

	# Common Defaults
	if [[ ${gem_os} == "MINGW64"* ]]; then	# MinGW shell on Windows.
		gem_host=mingw
#		gem_host=msvc
	elif [[ ${gem_os} == "CYGWIN"* ]]; then	# Linux shell.
		gem_host=cygwin
#		gem_host=mingw
	elif [[ ${gem_os} == "Linux"* ]]; then	# Linux shell.
		gem_host=linux
#		gem_host=mingw
#		gem_host=android_arm64_v8a
	fi

	gem_build_type=release
#	gem_build_type=debug
}

function gem_build_v_SetFlags
{
	gem_build_SetFlags

	gem_flags_configure="${gem_flags_configure}"
	gem_flags_c="${gem_flags_c} $(pkg-config --cflags-only-I sdl2)"
	gem_flags_cpp="${gem_flags_cpp}"
	gem_flags_cxx="${gem_flags_cxx}"
	gem_flags_ld="${gem_flags_ld}"
}

function gem_build_v_GetFilePath_src
{
	echo "$(pwd)/src/test"
}

function gem_build_v_GetFilePath_build
{
	echo "$(pwd)/build_tests/${gem_path_suffix}"
}

function gem_build_v_OnCommandLine_Configure_CMake
{
	gem_build_OnCommandLine_Configure_CMake
}

function gem_build_v_OnConfigure
{
	gem_build_v_DebugDumpVars
	gem_build_OnConfigure
}

function gem_build_v_OnCommandLine_Build
{
	gem_build_OnCommandLine_Build
}

function gem_build_v_OnBuild
{
	gem_build_v_DebugDumpVars
	gem_build_OnBuild
}

function gem_build_v_OnInstall
{
	# Since the tests aren't going to be installed, we'll copy the relevant
	# dlls into the build_tests directory, where the executables are.
	gem_build_OnCommandLine_Install

	if [[ ${gem_option_cmdline_only} -ne 0 ]]; then
		gem_script_v_Msg_NotQuiet "${gem_cmd_line_install}"
		return 1
	fi

	# The makefile doesn't support installing.
#	eval "${gem_cmd_line_install} ${gem_redirect_suffix_install}"

	if [[ ${gem_os} == "MINGW64"* ]]; then

		cp /c/msys64/mingw64/bin/libgcc_s_seh-1.dll ${gem_fullpath_install}/bin
		cp /c/msys64/mingw64/bin/libstdc++-6.dll ${gem_fullpath_install}/bin
		cp /c/msys64/mingw64/bin/libwinpthread-1.dll ${gem_fullpath_install}/bin

		gem_script_cp ${gem_fullpath_install}/bin/SDL2.dll ${gem_fullpath_build}

	elif [[ ${gem_os} == "CYGWIN"* ]]; then

		gem_script_cp ${gem_fullpath_install}/bin/SDL2.dll ${gem_fullpath_build}

		if [[ ${gem_host} == "cygwin" ]]; then	# Build for cygwin.
			cp /cygdrive/c/cygwin64/bin/cygwin1.dll ${gem_fullpath_build}
		fi
	fi
}

function gem_build_v_OnUninstall
{
	gem_build_OnUninstall
}

function gem_build_v_OnClean
{
	gem_build_OnClean
}

# =============================================================================
#                                       gem_Main
# =============================================================================
function gem_script_v_OnArg
{
	arg=$(echo ${1} | tr '[A-Z]' '[a-z]')	# Lowercase args.
	case ${arg} in
		*)	gem_build_OnArg "$@" ;	return $?
	esac
}


function gem_script_v_Main
{
	gem_build_Main "$@"
}
gem_script_v_Main $@
